# Use C++ build environment.
language: cpp

# Protobuf requires g++ (see https://github.com/google/protobuf/blob/master/src/README.md)
compiler:
    - gcc

# Cache dependencies to speed up the build.
cache:
    directories:
        - ${TRAVIS_BUILD_DIR}/deps/cmake
        - ${TRAVIS_BUILD_DIR}/deps/protobuf/install
        - ${TRAVIS_BUILD_DIR}/deps/boost/install

# Handle dependencies in separate directory.
before_install:
    - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
    - mkdir -p "${DEPS_DIR}"
    - cd "${DEPS_DIR}"

install:
    # Installs a recent version of CMake
    - |
        CMAKE_URL="https://cmake.org/files/v3.9/cmake-3.9.1-Linux-x86_64.tar.gz"
        if [ ! -f ${DEPS_DIR}/cmake/bin/cmake ] ; then
            mkdir -p cmake
            travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
        fi
        export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    # Installs a recent version of Protobuf
    - |
        PROTOBUF_URL="https://github.com/google/protobuf/releases/download/v3.4.0/protobuf-cpp-3.4.0.tar.gz"
        if [ ! -f ${DEPS_DIR}/protobuf/install/bin/protoc ] ; then
            cd "${DEPS_DIR}"
            mkdir -p protobuf
            travis_retry wget --no-check-certificate --quiet -O - ${PROTOBUF_URL} | tar --strip-components=1 -xz -C protobuf
            cd protobuf
            ./configure --prefix=${DEPS_DIR}/protobuf/install
            make
            make install
        fi
        export PATH=${DEPS_DIR}/protobuf/install/bin:${PATH}
    # Installs a recent version of Boost
    - |
        BOOST_URL="http://dl.bintray.com/boostorg/release/1.64.0/source/boost_1_64_0.tar.gz"
        if [ ! -f ${DEPS_DIR}/boost/install/lib/libboost_system.a ] ; then
            cd "${DEPS_DIR}"
            mkdir -p boost
            travis_retry wget --no-check-certificate --quiet -O - ${BOOST_URL} | tar --strip-components=1 -xz -C boost
            cd boost
            ./bootstrap.sh --prefix=${DEPS_DIR}/boost/install
                --with-libraries=system
                --with-libraries=program_options
                --with-libraries=thread
                --with-libraries=log
            ./b2 install
        fi
        export PATH=${DEPS_DIR}/boost/install/lib:${PATH}

# Change directory back to default build directory.
before_script:
    - cd "${TRAVIS_BUILD_DIR}"
    - cmake --version
    - protoc --version

# Run the build script.
script:
  - mkdir -p repost-common/generated/cpp
  - protoc --cpp_out="repost-common/generated/cpp" repost-common/repost.proto
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release
          -D CMAKE_PREFIX_PATH:PATH=${DEPS_DIR}/protobuf/install
          -D BOOST_ROOT:PATHNAME=${DEPS_DIR}/boost/install ..
  - cmake --build .
