sudo: false

# Enable C++ support
language: cpp

# Compiler selection
matrix:
  include:
    - os: linux
      compiler: gcc

addons:
  apt:
    sources:
      - boost-latest
    packages:
      - cmake
      - libboost-dev
      
cache:
  directories:
  - $HOME/protobuf
  
before_install:
  # Build protobuf 3.4.0 from sources if not found in cache
  - |
      if [ ! -d "$HOME/protobuf" ]; then
        PROTOBUF_URL="https://github.com/google/protobuf/releases/download/v3.4.0/protobuf-cpp-3.4.0.tar.gz"
        mkdir protobuf && travis_retry wget --no-check-certificate --quiet -O - ${PROTOBUF_URL} | tar --strip-components=1 -xz -C protobuf
        cd protobuf && ./configure --prefix=$HOME/protobuf && make && make install
        cd ..
      fi

# check what has been installed by listing contents of protobuf folder
before_script:
  - ls -R $HOME/protobuf
  
script:
  - mkdir -p repost-common/generated/cpp
  - $HOME/protobuf/bin/protoc --cpp_out="repost-common/generated/cpp" repost-common/repost.proto
  - mkdir build && cd build && cmake .. && make
