sudo: false

# Enable C++ support
language: cpp

# Compiler selection
matrix:
  include:
    - os: linux
      compiler: gcc

addons:
  apt:
    sources:
      - boost-latest
    packages:
      - cmake
      - libboost-dev
      
cache:
  directories:
  - $HOME/protobuf
  
before_install:
  - bash install-protobuf.sh

# check what has been installed by listing contents of protobuf folder
before_script:
  - ls -R $HOME/protobuf
  
script:
  - mkdir -p repost-common/generated/cpp
  - $HOME/protobuf/bin/protoc --cpp_out="repost-common/generated/cpp" repost-common/repost.proto
  - mkdir build && cd build && cmake .. && make
